name: aromatherapy
description: Aromatherapy app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+3

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  material_segmented_control: ^3.1.2
  tab_indicator_styler: ^2.0.0

  url_launcher: ^6.0.2
  provider: ^6.0.1
  google_fonts: ^2.2.0 # TODO:: replace it with one font (if we can save app size)
  package_info_plus: ^1.3.0
  introduction_screen: ^3.0.0 #TODO:: implement it

  # Firebase services
  firebase_core: ^1.7.0
  firebase_auth: ^3.1.3
  google_sign_in: ^5.2.1
  flutter_facebook_auth: ^3.5.6
  cloud_firestore: ^3.1.0
  purchases_flutter: ^3.9.5

  #Revenflutter pub add purchase_paywallucat
  rflutter_alert: ^2.0.0
  animated_bottom_navigation_bar: ^0.3.2
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/

